production:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>
      options:
        ssl: true
        retry_writes: true

development:
  clients:
    default:
      uri: <%= ENV['MONGODB_URI'] %>